### ISSUE TITLE
upgrading Camera to high definition 

### ISSUE THREAD

**Issue by ed816607** [Ruud14/SecurityCamera#6]
Hello, There is no issue with the current coding ,I have used your coding to run a standard Pi camera on the Pi 4 , However now I want to use a higher defination camera with Infrared, for night night monitoring, I install a ARDU 16mb mini camera, but its uses Libcamera to operate the camera,  I installed all the nessary drivers for the Camera to work(which it does on test to take a snap shot) but wont work with your current coding. I understand it has something to do with the area of Picamera  and Libcamera, but unsure how (if possibel) to modify the python script to use Libcamera. Any Guidance would be helpful to continue using your script. Kind Regards Martin (very basic knowledge of python) complete beginner.

**Comment by Ruud14** [comment]
Hi Martin,

I did some reading online and the picamera library used here apparently only works with the legacy raspberry pi camera stack.
The newer cameras (like yours) work with [picamera2](https://pypi.org/project/picamera2/0.2.2/) (which uses libcamera under the hood). 

I don't think changing the code to use picamera2 instead of picamera would be that much work, though I unfortunately cannot do this myself as I don't have a new generation camera to test with.  

I'm sure there are more people online that had to migrate from picamera to picamera2 though, so you could always give migrating the code yourself a try.

Kind regards,

Ruud

**Comment by ed816607** [comment]
Hi Rudd 

Cheers for getting back to me so quickly, this all all so new to me and a big learning curve. It only took 3 weeks to get the new camera to take a picture, so I will continue to keep trying. Kind Regards Martin
